<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>edp</string>
	</array>
	<key>name</key>
	<string>FreeFem++</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>type</string>
			<key>match</key>
			<string>\b(asm|__asm__|auto|bool|_Bool|char|_Complex|double|enum|float|_Imaginary|int|long|short|signed|struct|typedef|union|unsigned|void|border|Cmatrix|complex|fespace|func|ifstream|matrix|mesh|mesh3|ofstream|problem|R3|real|solve|string|varf)\b</string>
			<key>name</key>
			<string>storage.type.c</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>functions</string>
			<key>match</key>
			<string>\b(break|case|continue|default|do|else|for|goto|if|_Pragma|return|switch|while|average|jump|mean|otherside|int1d|int2d|intalledges|on|dn|dx|dxx|dxy|dy|dyx|dyy|dz|interpolate|set|sort|change|plot|adaptmesh|buildmesh|buildmeshborder|checkmovemesh|emptymesh|movemesh|readmesh|savemesh|splitmesh|square|triangulate|trunc|abs|acos|acosh|arg|asin|asinh|atan|atan2|atanh|ceil|conj|cos|cosh|exp|floor|imag|log|log10|max|min|norm|polar|pow|sin|sinh|sqrt|tan|tanh|randinit|randint31|randint32|randreal1|randreal2|randreal3|randint32|randint31|randreal1|randreadl2|randreal3|randres53|randinit|rint|ciel|j0|j1|jn|y0|y1|yn|tgamma|erf|erfc)\b</string>
			<key>name</key>
			<string>keyword.control.c</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keyword</string>
			<key>match</key>
			<string>\b(P0|P0edge|P0VF|P1|P1b|P1dc|P1nc|P2|P2b|P2dc|P2h|RT0|RT0Ortho|RTmodif|qf1pE|qf1pElump|qf1pT|qf1pTlump|qf2pE|qf2pT|qf2pT4P1|qf3pE|qf5pT|qf7pT|qf9pT)\b</string>
			<key>name</key>
			<string>entity.name.function.preprocessor.c</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>parameter</string>
			<key>match</key>
			<string>\b(abserror|anisomax|append|aspectratio|bb|binside|bmat|bw|cadna|clean|cmm|cutoff|dimKrylov|eps|err|errg|factorize|fill|grey|hmax|hmin|hsv|init|inquire|inside|IsMetric|iso|ivalue|keepbackvertices|maxit|maxsubdiv|metric|nbarrow|nev|nbiso|nbiter|nbiterline|nbjacoby|nbsmooth|nbvx|ncv|nomeshgeneration|omega|op|optimize|periodic|power|precon|prev|ps|qfe|qfnbpE|qfnbpT|qforder|qft|ratio|rescaling|save|sigma|solver|split|splitin2|splitpbedge|strategy|sym|tgv|thetamax|tol|tolpivot|tolpivotsym|value|varrow|vector|veps|viso|wait|WindowIndex)\b</string>
			<key>name</key>
			<string>entity.name.function.preprocessor.c</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>comment block</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.c</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>reserved constants</string>
			<key>match</key>
			<string>\b(pi|NULL|true|false|TRUE|FALSE)\b</string>
			<key>name</key>
			<string>constant.language.c</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.c</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>strings with double quotes</string>
			<key>end</key>
			<string>\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.c</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.c</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*#\s*(define|defined|elif|else|if|ifdef|ifndef|line|pragma|undef)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.c</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=(?://|/\*))|$</string>
			<key>name</key>
			<string>meta.preprocessor.c</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>numeric constants</string>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.c</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operators</string>
			<key>match</key>
			<string>\s*(=|==|~=|&lt;|&lt;=|&gt;|&gt;=|&amp;|&amp;&amp;|:|\||\|\||\+|-|\*|\.\*|(?=/)|\./|\\|\.\\|\^|\.\^)\s*</string>
			<key>name</key>
			<string>keyword.operator.symbols.matlab</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>comment</key>
			<string>comment line</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.banner.c++</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.FreeFem++</string>
	<key>uuid</key>
	<string>88f5b3d3-5019-47b9-924b-e114f151f9c8</string>
</dict>
</plist>
